### ISSUE TITLE
Proposal: Separate protobuf and json parsers

### ISSUE THREAD

**Issue by wi101** [moia-oss/teleproto#228]
Hey 👋 

We're using teleproto in a project to convert to protobuf and we use Spark. We got this error:

```
ERROR SparkHadoopWriter: Aborting job job_20221214135935241508088406623081_0074.
org.apache.spark.SparkException: Job aborted due to stage failure: Task serialization failed: java.lang.NoClassDefFoundError: org/json4s/JsonAST$JValue
java.lang.NoClassDefFoundError: org/json4s/JsonAST$JValue
```
Because Spark is using an older json4s version
we had to exclude the `"com.thesamet.scalapb" %% "scalapb-json4s` to make it work.

- **Currently:**  
`VersionedModelReader` has `fromJson` and `fromProto`
and `VersionedModelWriter` has `toJson` and `toProto` 

- **Suggestion:**
To have a separate module for json and for proto that will be published in separate jars

**Comment by saeltz** [comment]
Hey Wiem,

thanks for your proposal!

We're actively investigating support for Scala 3 at the moment and don't want to spend too many resources on the Scala 2 version.

An easier alternative might be to [declare the dependency on `scalapb-json4s` as optional](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) in this library.
Do you think this would solve your issue? If so, I'd happily do the change. If not, I'll take another look at modularising the library.

**Comment by wi101** [comment]
I think the suggested alternative would be helpful :) thank you!
